services:
  astrowind-dev:
    image: node:lts
    container_name: astrowind-dev
    ports:
      - 4321:4321
    working_dir: /app
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    command: >
      bash -c "npm install && 
              npx astro dev --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    env_file:
      - .env.local
    depends_on:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog-dev
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  node_modules: